[workspace]
members = [
    "encapfn-tock",
    "demo/nrf52840dk",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Leon Schuermann <leon@is.currently.online>"]
edition = "2021"

[workspace.dependencies]
kernel = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
nrf52840 = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
nrf52840dk = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
capsules-core = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
capsules-extra = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
capsules-system = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
components = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
tock-tbf = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }
rv32i = { git = "https://github.com/tock/tock", rev = "650812b962e9cf1527ed1fa3322c43dcec7cadae" }

encapfn = { git = "https://github.com/encapfn/encapfn", rev = "825b6ff0a5ce840a89edd4ce03c79d47f5d39b07" }

[profile.dev]
panic = "abort"
lto = false
opt-level = "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true
codegen-units = 1
