[package]
name = "encapfn-tock-lwip"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]
path = "rust/lib.rs"

[dependencies]
kernel.workspace = true
encapfn.workspace = true
encapfn-tock.path = "../../encapfn-tock"

[build-dependencies]
bindgen.workspace = true
cc = "1.0.90"
